export const ActionTypes = {
  //AUTH
  SET_USER: "SET_USER",
  ADD_USER: "ADD_USER",
  LOGOUT_USER: "LOGOUT_USER",
  FORGOT_PASSWORD: "FORGOT_PASSWORD",

  //PRODUCTS

  GET_PRODUCTS: "GET_PRODUCTS",
  SET_NEW_ARRIVALS: "SET_NEW_ARRIVALS",
  SET_TRENDING_NOW: "SET_TRENDING_NOW",
  SET_BEST_SELLERS: "SET_BEST_SELLERS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",
  REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT",
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_CATEGORY: "GET_CATEGORY",

  SET_AUTHOR: "SET_AUTHOR",
  GET_AUTHORS: "GET_AUTHORS",
  GET_SINGLE_AUTHOR: "GET_SINGLE_AUTHOR",

  //CART
  GET_CART: "GET_CART",
  ADD_TO_CART: "ADD_TO_CART",

  //WISHLIST
  ADD_TO_WISHLIST: "ADD_TO_WISHLIST",
  GET_WISHLIST: "GET_WISHLIST",
};
